[package]
name = "devmeld"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
devmeld-resources = { path = "../resources" }
devmeld-publication = { path = "../publication" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
jsonschema = { version = "0.55.0", default-features = false }
file-id = "0.2.3"

[lints]
workspace = true
