//! Fixed publication wording. Authored content never passes through translation.
use crate::{Result, error};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize)]
pub enum OutputLanguage {
    #[default]
    #[serde(rename = "en")]
    English,
    #[serde(rename = "zh-CN")]
    SimplifiedChinese,
}

impl<'de> Deserialize<'de> for OutputLanguage {
    fn deserialize<D: serde::Deserializer<'de>>(
        deserializer: D,
    ) -> std::result::Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Self::parse(&value).map_err(serde::de::Error::custom)
    }
}

impl OutputLanguage {
    pub(crate) fn parse(value: &str) -> Result<Self> {
        match value {
            "en" => Ok(Self::English),
            "zh-CN" => Ok(Self::SimplifiedChinese),
            _ => Err(error(format!(
                "unsupported output language {value:?}; expected en or zh-CN"
            ))),
        }
    }

    pub(crate) fn is_default(&self) -> bool {
        *self == Self::English
    }

    pub(crate) fn messages(self) -> &'static Messages {
        match self {
            Self::English => &ENGLISH,
            Self::SimplifiedChinese => &SIMPLIFIED_CHINESE,
        }
    }
}

// Both sets must provide every field; no string-key lookup or silent fallback.
pub(crate) struct Messages {
    pub context_notes: &'static str,
    pub context_information: &'static str,
    pub annotation_tags: &'static str,
    pub source_attributes: &'static str,
    pub context_heading: &'static str,
    pub navigation_notice: &'static str,
    pub resource_marker: &'static str,
    pub maintenance_notice: &'static str,
    pub references_heading: &'static str,
    pub groups_heading: &'static str,
    pub resources_heading: &'static str,
    pub original_source: &'static str,
    pub access_heading: &'static str,
    pub access_guidance: &'static str,
    pub associated_resource: &'static str,
    pub project_heading: &'static str,
    pub entry_intro: &'static str,
    pub navigation_label: &'static str,
    pub entry_after_link: &'static str,
    pub local_path: &'static str,
    pub shared_maintenance: &'static str,
}

const ENGLISH: Messages = Messages {
    context_notes: "Context notes",
    context_information: "Context information",
    annotation_tags: "Tags",
    source_attributes: "Source-declared attributes",
    shared_maintenance: "Surrounding project instructions remain author-owned.",
    local_path: "Local path",
    context_heading: "Context",
    navigation_notice: "Generated by DevMeld. Read these files without running DevMeld.\nOnly reflects the last successful synchronization.",
    resource_marker: "Generated by DevMeld; do not edit directly.",
    maintenance_notice: "Maintain generated entries, navigation and registration through DevMeld; do not edit them directly. Edit original sources according to their owners' rules.",
    references_heading: "References",
    groups_heading: "Groups",
    resources_heading: "Resources",
    original_source: "View source",
    access_heading: "Access guidance",
    access_guidance: "These are declared associations, not exclusive selections or verified availability. Respect applicable explicit selection; do not silently substitute. Otherwise prefer an eligible existing option requiring no dependency, environment or installation change: project-managed first, then verified local/system options valid in the current task scope. Only then propose a change. Machine presence is not eligibility. Selection does not authorize installation, dependency changes, environment creation, system modification or execution beyond the task's authority.",
    associated_resource: "Associated resource",
    project_heading: "Project context",
    entry_intro: "Generated by DevMeld. Follow ",
    navigation_label: "context navigation",
    entry_after_link: " and choose relevant resources.\nNo running DevMeld process is needed.",
};

const SIMPLIFIED_CHINESE: Messages = Messages {
    context_notes: "使用说明",
    context_information: "上下文信息",
    annotation_tags: "标签",
    source_attributes: "源文件属性",
    shared_maintenance: "片段之外的项目说明仍由作者维护。",
    local_path: "本地路径",
    context_heading: "上下文",
    navigation_notice: "由 DevMeld 生成。读取这些文件无需运行 DevMeld。\n内容仅反映最近一次成功同步的结果。",
    resource_marker: "DevMeld 生成，请勿直接修改。",
    maintenance_notice: "生成的入口、索引和注册配置须通过 DevMeld 维护，请勿直接修改。原始资料按其所有者的规则编辑。",
    references_heading: "相关资料",
    groups_heading: "分组",
    resources_heading: "资源",
    original_source: "查看来源",
    access_heading: "接入指引",
    access_guidance: "以下为已声明的关联，不代表排他性选择或已验证的可用性。应遵循适用的明确选择，不得静默替换。未明确选择时，优先复用无需新增依赖、创建环境或安装的现有合格方案：优先项目管理的方案，其次是当前任务范围内已验证可调用、兼容且获授权的本地或系统方案。仅在没有合适的现有方案时提出变更。机器上存在某工具不代表当前任务可用。选择工具不等于授权安装、修改依赖、创建环境、修改系统或执行超出当前任务授权的操作。",
    associated_resource: "关联资源",
    project_heading: "项目上下文",
    entry_intro: "由 DevMeld 生成。请通过 ",
    navigation_label: "上下文索引",
    entry_after_link: " 按需选择相关资源。\n无需运行 DevMeld 进程。",
};
