use crate::{
    Result,
    declarations::Config,
    error,
    storage::{Plan, resolve},
};
use std::collections::BTreeMap;
use std::path::{Component, Path, PathBuf};

pub(crate) fn text(value: &str) -> String {
    value
        .chars()
        .flat_map(|c| match c {
            '&' => "&amp;".chars().collect::<Vec<_>>(),
            '<' => "&lt;".chars().collect(),
            '>' => "&gt;".chars().collect(),
            '\n' | '\r' => " ".chars().collect(),
            '\\' | '`' | '*' | '_' | '[' | ']' | '(' | ')' | '#' | '!' | '|' => vec!['\\', c],
            _ if c.is_control() => vec![' '],
            _ => vec![c],
        })
        .collect()
}
pub(crate) fn link(from: &Path, to: &Path) -> Result<String> {
    let parent = from.parent().ok_or_else(|| error("link has no parent"))?;
    let a: Vec<_> = parent.components().collect();
    let b: Vec<_> = to.components().collect();
    if a.first() != b.first() {
        return Err(error(
            "entry/source must share a filesystem root for portable relative links",
        ));
    }
    let common = a.iter().zip(&b).take_while(|(a, b)| a == b).count();
    let mut parts = vec!["..".to_owned(); a.len() - common];
    for component in &b[common..] {
        if let Component::Normal(value) = component {
            let value = value
                .to_str()
                .ok_or_else(|| error("non-Unicode paths are not supported in Markdown links"))?;
            let encoded: String = value
                .bytes()
                .map(|byte| {
                    if byte.is_ascii_alphanumeric() || b"-_.~".contains(&byte) {
                        (byte as char).to_string()
                    } else {
                        format!("%{byte:02X}")
                    }
                })
                .collect();
            parts.push(encoded);
        }
    }
    Ok(parts.join("/"))
}
pub(crate) fn publication(
    plan: &mut Plan,
    config: &Config,
    resources: &devmeld_resources::Resources,
) -> Result<BTreeMap<PathBuf, Vec<u8>>> {
    let directory = resolve(plan.root(), &config.publication.directory)?;
    let index = directory.join("index.md");
    let config_path = plan.root().join(".devmeld/context.json");
    let mut files = BTreeMap::new();
    let mut navigation = String::from(
        "# Context\n\nGenerated by DevMeld. Read these files without running DevMeld.\nOnly reflects the last successful synchronization. Do not edit generated files.\n\n",
    );
    for resource in resources.iter() {
        let id = resource.id().as_str();
        let page = directory.join(format!("r-{id}.md"));
        navigation.push_str(&format!(
            "- [{}]({}) — {}\n",
            text(resource.title()),
            link(&index, &page)?,
            text(resource.summary())
        ));
        let mut content = format!(
            "# {}\n\n{}\n\nGenerated by DevMeld; update the original source or use DevMeld to change registration.\n\n[Original source]({})\n\n[Managed registration]({})\n",
            text(resource.title()),
            text(resource.summary()),
            link(&page, resource.source())?,
            link(&page, &config_path)?
        );
        for (key, value) in resource.attributes() {
            content.push_str(&format!("\n- {}: {}", text(key), text(value)));
        }
        content.push_str("\n\n");
        for (label, target) in resource.references() {
            content.push_str(&format!("- [{}]({})\n", text(label), link(&page, target)?));
        }
        let mut tools: Vec<_> = config
            .access
            .iter()
            .filter(|a| a.resource == id)
            .map(|a| a.tool.as_str())
            .collect();
        tools.sort();
        if !tools.is_empty() {
            content.push_str("\n## Access guidance\n\n");
            content.push_str(devmeld_resources::ACCESS_GUIDANCE);
            content.push_str("\n\n");
            for tool in tools {
                content.push_str(&format!(
                    "- [Associated resource: {}]({})\n",
                    text(tool),
                    link(&page, &directory.join(format!("r-{tool}.md")))?
                ));
            }
        }
        files.insert(page, content.into_bytes());
    }
    navigation.push_str(&format!(
        "\n[Managed registration]({})\n",
        link(&index, &config_path)?
    ));
    files.insert(index.clone(), navigation.into_bytes());
    for entry in &config.publication.entries {
        if entry.kind != "file" {
            return Err(error("unsupported entry kind"));
        }
        let path = resolve(plan.root(), &entry.path)?;
        let content = format!(
            "# Project context\n\nGenerated by DevMeld. Follow [context navigation]({}) and choose relevant resources.\nNo running DevMeld process is needed. Do not edit this generated entry.\n",
            link(&path, &index)?
        );
        if files.insert(path, content.into_bytes()).is_some() {
            return Err(error("duplicate publication target"));
        }
    }
    Ok(files)
}
